services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/usr/src/app
    command: npm run dev  # o npm start según tu script
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  pgdata:
