name: Node.js Backend Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Crear archivo .env para Docker
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Construir y levantar contenedores
        run: docker compose up -d --build

      - name: Verificar estado de los contenedores
        run: docker compose ps

      - name: Esperar a que los servicios estén listos
        run: sleep 20

      - name: Ver logs del backend si falla
        if: failure()
        run: docker compose logs backend

      - name: Ejecutar tests en el contenedor backend
        run: docker compose run --rm backend npm test

      - name: Apagar contenedores
        if: always()
        run: docker compose down