name: Node.js Backend Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: stock_db
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Construir y levantar Docker
        run: docker compose up -d --build

      - name: Esperar a que el backend esté listo
        run: sleep 10

      - name: Correr tests dentro del contenedor
        run: docker compose exec backend npm test

      - name: Apagar contenedores
        if: always()
        run: docker compose down
