name: Node.js Backend Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Crear archivo .env para Docker
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Construir y levantar Docker Compose
        run: docker compose up -d --build

      - name: Instalar dependencias dentro del contenedor backend
        run: docker compose exec backend npm install

      - name: Esperar a que el backend esté listo
        run: sleep 10

      - name: Ejecutar tests en el contenedor backend
        run: docker compose exec backend npm test

      - name: Apagar contenedores
        if: always()
        run: docker compose down
